### ISSUE TITLE
Threat model issue: warning against non-soft adversaries

### ISSUE THREAD

**Issue by AnonyPla** [zorggish/FractalCryptGUI#5]
Please look and consider the old but relevant: https://defuse.ca/truecrypt-plausible-deniability-useless-by-game-theory.htm

The same reasoning would be valid for your tool as well.

If your adversary is a soft and lawful adversary, plausible deniability is a reasonable measure.

If your adversary on the contrary is a hard adversary resorting to rubber-hose cryptanalysis (xkcd 5$ wrench, enhanced interrogation, or just plain torture), then this tool might worsen the situation considerably.

**Comment by zorggish** [comment]
This article is about the problem of using TrueCrypt, which allows you to create a single hidden layer;
In case TrueCrypt usage is detected, the requirement to give out the hidden layer password would be quite reasonable, because then you can be sure that the container is decrypted in its entirety.
In the case of FractalCrypt, only part of the container can be decrypted, even knowing all the passwords; hence, denying the existence of truly secret data can be quite convincing, for example, by first giving out unclassified, and after a long interrogation giving out semisecret ones.

In addition, the article states that
> In other scenarios the feature can be useful. If the attacker has limited resources (i.e. can only torture you for 30 minutes), or if you are "innocent until proven guilty" under the law, then it can be advantageous to use a hidden volume. Just don't recommend TrueCrypt to your friends in North Korea, or at least make sure they use a hidden volume. 

In most situations, such as a police raid or criminal robbery, you will not be tortured to death.
However, it is really better not to use FractalCrypt in North Korea.

Translated with www.DeepL.com/Translator (free version)

**Comment by zorggomat** [comment]
This article is about the problem of using TrueCrypt, which allows you to create a single hidden layer;
In case TrueCrypt usage is detected, the requirement to give out the hidden layer password would be quite reasonable, because then you can be sure that the container is decrypted in its entirety.
In the case of FractalCrypt, only part of the container can be decrypted, even knowing all the passwords; hence, denying the existence of truly secret data can be quite convincing, for example, by first giving out unclassified, and after a long interrogation giving out semisecret ones.

In addition, the article states that

    In other scenarios the feature can be useful. If the attacker has limited resources (i.e. can only torture you for 30 minutes), or if you are "innocent until proven guilty" under the law, then it can be advantageous to use a hidden volume. Just don't recommend TrueCrypt to your friends in North Korea, or at least make sure they use a hidden volume.

In most situations, such as a police raid or criminal robbery, you will not be tortured to death.
However, it is really better not to use FractalCrypt in North Korea.

**Comment by AnonyPla** [comment]
The point is, if you use FractalCrypt against someone willing to torture you, they have zero incentive to not keep torturing you forever just in case you're not giving all the keys. 

Your README is a bit misleading in making think it could be a good idea to use your project against those adversaries when it's not.

**Comment by zorggomat** [comment]
FractalCrypt is used to create the convincing illusion that you have issued all keys.
Being tortured for having FractalCrypt is like being tortured for suggesting that you may have buried a box of classified information somewhere in the woods.
If they want to torture you to death, no program can stop them from doing it. If they want to test you for some files on the disk, with FractalCrypt you can deny it convincingly enough.

**Comment by AnonyPla** [comment]
> 
> 
> FractalCrypt is used to create the convincing illusion that you have issued all keys.
> Being tortured for having FractalCrypt is like being tortured for suggesting that you may have buried a box of classified information somewhere in the woods.

Except that, in this case, they found you with all the necessary tools to bury something in the woods on you.

> If they want to torture you to death, no program can stop them from doing it. If they want to test you for some files on the disk, with FractalCrypt you can deny it convincingly enough.
